### PR TITLE
Added output for total files processed.

### PR DESCRIPTION
**Pull request by 58bits**
Added output for total files processed.

The current set of tests include 0, 1, and 2 files processed.

(my editor settings are 2 spaces for tabs, so apologies for the format changes)

### CODE REVIEW

**Comment by sindresorhus** [comment]
No thanks. If you want this get it added to grunt itself. Not interested in adding custom functionality that could be in grunt and available for all grunt tasks. Your way every single grunt task would have to implement this. https://github.com/gruntjs/grunt/issues/new

**Comment by 58bits** [comment]
grunt-contrib-clean
grunt-contrib-uglify
grunt-postcss

... to name a few, all implement this feature.

**Comment by sindresorhus** [comment]
It's only task specific because you decided to use the wording `stylesheets` instead of `files`. Otherwise it's totally generic.

**Comment by 58bits** [comment]
Yes - and grunt-contrib-clean uses '>> 2 paths cleaned', and grunt-postcss uses '>> 3 processed stylesheets created.'  Anyway - I thought it would be helpful to see informative output, and so I'm not sure why you're so resistant.

**Comment by sindresorhus** [comment]
I know, but it could be `files` and be just as informative. The grunt API could support a custom word if that's important.

I've made a lot of grunt tasks and I'm not interested in getting requests to manually reimplement this in all of them when it could be implemented once in grunt. I'm also very much against duplication and wasted effort like that. Sure, it's just a few lines, but that saying is always a slippery slope. I've been there many times. Don't want to sound difficult, but I've stopped doing it the easy way just because it's easy.

**Pull request closed without merging**
