### PR TITLE
Add --quiet option equivalent

### PR DESCRIPTION
**Pull request by DaSchTour**
Add possibility to suppress warnings like described in SASS-Lang reference and like possible with grunt-contrib-sass

### CODE REVIEW

**Comment by sindresorhus** [comment]
Those are errors though, not warnings. I don't think it makes sense to ignore those.

**Comment by DaSchTour** [comment]
So in which place are the warning generated?

**Comment by sindresorhus** [comment]
I don't know, sorry. Do some research.

**Comment by DaSchTour** [comment]
Well so it looks like this plugin treats warnings as errors and so doesn't follow the SASS specification of how to treat @warn https://www.sass-lang.com/documentation/file.SASS_REFERENCE.html#_6

**Comment by xzyfer** [comment]
`@error` are errors and `@warn` are warning. If I'm understanding correctly you wish to replicated the `--quiet` flag that both node-sass and ruby-sass provide via their CLIs. In that case this patch is incorrect.

What you should be doing is passing a `quiet` option to the node-sass `render` call. However node-sass does not currently support the quiet option. You should open an issue with node-sass to enable `quiet` to be passed to `render`/`renderSync`.

**Comment by DaSchTour** [comment]
@xzyfer okay, that's even worser than I ever could imagine :see_no_evil:

**Pull request closed without merging**
